In [12]:
from sklearn.datasets import make_blobs
import numpy as np
from sklearn.mixture import GaussianMixture
blob_centers = np.array(
    [[ 0.2,  2.3],
     [-1.5 ,  2.3],
     [-2.8,  1.8],
     [-2.8,  2.8],
     [-2.8,  1.3]])
blob_std = np.array([0.4, 0.3, 0.1, 0.1, 0.1])

X, y = make_blobs(n_samples=2000, centers=blob_centers,
                  cluster_std=blob_std, random_state=7)



下面的例子，主要是看看init，对于最后的结果，有没有影响

In [13]:
init_means = np.array([[1,2],[2,1],[0,1]])
init_weights = np.array([0.1,0.2,0.7])
gm_classification = GaussianMixture(n_components=3,n_init=10,means_init=init_means,weights_init=init_weights)
gm_classification.fit_predict(X)
gm_classification.means_,gm_classification.weights_

(array([[-2.11461964,  2.53020634],
        [-2.80378572,  1.55104249],
        [ 0.2125564 ,  2.27344516]]),
 array([0.40590107, 0.39987525, 0.19422368]))

In [14]:
gm_classification = GaussianMixture(n_components=3,n_init=10)
gm_classification.fit_predict(X)
gm_classification.means_,gm_classification.weights_


(array([[-1.48543693,  2.28573643],
        [ 0.19937187,  2.25813691],
        [-2.80278963,  1.96665812]]),
 array([0.19978216, 0.20032189, 0.59989596]))